[build]
  publish = "dist"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "18"


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/api/*"
  to = "https://www.hut-reservation.org/api/:splat"
  status = 200
  force = true
  headers = {origin = "https://www.hut-reservation.org"}

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/api/v1/reservation/hutInfo/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Netlify-CDN-Cache-Control = "public, max-age=86400, stale-while-revalidate=3600"

[[headers]]
  for = "/api/v1/reservation/search/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Netlify-CDN-Cache-Control = "no-cache"
